from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

TEXT_EXTENSIONS = {
    '.md', '.mdc', '.txt', '.json', '.jsonc', '.yaml', '.yml', '.toml', '.py', '.js', '.css', '.html', '.schema', '.schema.json'
}

SKIP_DIRS = {'.git', '.pytest_cache', '__pycache__', '.mypy_cache', '.venv', 'node_modules'}


@dataclass(slots=True)
class RepoEntry:
    path: str
    kind: str
    size: int


CATEGORY_PREFIXES = [
    ('research-workspace/', 'workspace'),
    ('skills/', 'skill'),
    ('agents/', 'agent'),
    ('tools/', 'tool'),
    ('apps/', 'app'),
    ('docs/', 'doc'),
    ('graph/', 'graph'),
    ('contexts/', 'context'),
    ('rules/', 'rule'),
    ('schemas/', 'schema'),
    ('examples/', 'example'),
    ('tests/', 'test'),
    ('packages/', 'package'),
]

WORKSPACE_ROOT = 'research-workspace'
WORKSPACE_SECTION_META = {
    'reports': {
        'label': 'Compiled reports',
        'tone': 'purple',
        'description': 'Review markdown, HTML, and published synthesis reports generated by openResearch.',
    },
    'notes': {
        'label': 'Literature notes',
        'tone': 'yellow',
        'description': 'Read structured paper notes, extraction summaries, and topic writeups.',
    },
    'library': {
        'label': 'Source library',
        'tone': 'cyan',
        'description': 'Track PDFs, repo snapshots, databases, and other compiled assets.',
    },
}


def classify_path(rel_path: str) -> str:
    for prefix, kind in CATEGORY_PREFIXES:
        if rel_path.startswith(prefix):
            return kind
    return 'file'


def resolve_repo_path(repo_root: Path, rel_path: str = '.') -> Path:
    rel_path = rel_path.strip() or '.'
    rel_path = rel_path.lstrip('/')
    target = (repo_root / rel_path).resolve() if rel_path != '.' else repo_root.resolve()
    if repo_root.resolve() not in target.parents and target != repo_root.resolve():
        raise ValueError('Path escapes repo root')
    return target


def iter_repo_files(repo_root: Path, rel_root: str = '.') -> Iterable[Path]:
    base_root = resolve_repo_path(repo_root, rel_root)
    if not base_root.exists():
        return

    for path in base_root.rglob('*'):
        if path.is_dir():
            if path.name in SKIP_DIRS:
                continue
            continue
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        yield path


def build_tree(repo_root: Path, rel_root: str = '.') -> dict:
    base_root = resolve_repo_path(repo_root, rel_root)
    root_path = '.' if rel_root == '.' else rel_root.strip('/').replace('\\', '/')
    root = {'name': base_root.name, 'path': root_path, 'kind': 'dir', 'children': []}
    path_map: dict[str, dict] = {root_path: root}

    for file_path in sorted(iter_repo_files(repo_root, rel_root)):
        rel = file_path.relative_to(repo_root).as_posix()
        current_parent = root
        parent_key = root_path
        relative_to_base = file_path.relative_to(base_root).as_posix()
        parts = relative_to_base.split('/')
        for idx, part in enumerate(parts):
            is_last = idx == len(parts) - 1
            child_path = part if parent_key == '.' else f'{parent_key}/{part}'
            existing = path_map.get(child_path)
            if existing is None:
                node = {
                    'name': part,
                    'path': child_path,
                    'kind': 'file' if is_last else 'dir',
                }
                if is_last:
                    node['category'] = classify_path(rel)
                    node['size'] = file_path.stat().st_size
                else:
                    node['children'] = []
                current_parent['children'].append(node)
                path_map[child_path] = node
                existing = node
            current_parent = existing
            parent_key = child_path
    return root


def list_repo_entries(repo_root: Path) -> list[RepoEntry]:
    entries: list[RepoEntry] = []
    for file_path in sorted(iter_repo_files(repo_root)):
        rel = file_path.relative_to(repo_root).as_posix()
        entries.append(RepoEntry(path=rel, kind=classify_path(rel), size=file_path.stat().st_size))
    return entries


def list_repo_entries_in(repo_root: Path, rel_root: str) -> list[RepoEntry]:
    entries: list[RepoEntry] = []
    for file_path in sorted(iter_repo_files(repo_root, rel_root)):
        rel = file_path.relative_to(repo_root).as_posix()
        entries.append(RepoEntry(path=rel, kind=classify_path(rel), size=file_path.stat().st_size))
    return entries


def search_repo(repo_root: Path, query: str, limit: int = 50) -> list[dict]:
    query = query.strip().lower()
    if not query:
        return []

    results: list[dict] = []
    for entry in list_repo_entries(repo_root):
        score = 0
        lower = entry.path.lower()
        if query in lower:
            score += 5
        if Path(lower).name.startswith(query):
            score += 4
        if f'/{query}' in lower:
            score += 2
        if score == 0:
            continue
        results.append({'path': entry.path, 'kind': entry.kind, 'size': entry.size, 'score': score})

    results.sort(key=lambda item: (-item['score'], item['path']))
    return results[:limit]


def read_text_file(repo_root: Path, rel_path: str, max_chars: int = 200_000) -> dict:
    rel_path = rel_path.lstrip('/')
    file_path = resolve_repo_path(repo_root, rel_path)
    if not file_path.exists() or not file_path.is_file():
        raise FileNotFoundError(rel_path)

    ext = file_path.suffix.lower()
    if ext not in TEXT_EXTENSIONS and file_path.name not in {'AGENTS.md', 'SKILL.md', 'Makefile', '.env.example'}:
        return {
            'path': rel_path,
            'kind': classify_path(rel_path),
            'content': f'Binary or non-text preview unavailable in the hub viewer.\n\nPath: {rel_path}\nSize: {file_path.stat().st_size} bytes',
            'truncated': False,
            'binary': True,
            'size': file_path.stat().st_size,
        }

    text = file_path.read_text(encoding='utf-8', errors='replace')
    truncated = len(text) > max_chars
    if truncated:
        text = text[:max_chars]
    return {
        'path': rel_path,
        'kind': classify_path(rel_path),
        'content': text,
        'truncated': truncated,
        'binary': False,
        'size': file_path.stat().st_size,
    }


def summarize_repo(repo_root: Path) -> dict:
    entries = list_repo_entries(repo_root)
    by_kind: dict[str, int] = {}
    for entry in entries:
        by_kind[entry.kind] = by_kind.get(entry.kind, 0) + 1

    return {
        'repo_name': repo_root.name,
        'file_count': len(entries),
        'by_kind': by_kind,
        'top_level': sorted({p.path.split('/')[0] for p in entries}),
    }


def workspace_bucket(path: str) -> str:
    normalized = path.replace('\\', '/')
    if normalized.startswith(f'{WORKSPACE_ROOT}/reports/'):
        return 'reports'
    if normalized.startswith(f'{WORKSPACE_ROOT}/notes/'):
        return 'notes'
    return 'library'


def workspace_item_title(path: str) -> str:
    return Path(path).stem.replace('-', ' ').replace('_', ' ') or Path(path).name


def summarize_workspace(repo_root: Path) -> dict:
    workspace_root = resolve_repo_path(repo_root, WORKSPACE_ROOT)
    if not workspace_root.exists():
        return {
            'root': f'{WORKSPACE_ROOT}/',
            'exists': False,
            'file_count': 0,
            'total_size': 0,
            'stats': [],
            'sections': [],
            'storage': [],
            'featured': None,
        }

    entries = [entry for entry in list_repo_entries_in(repo_root, WORKSPACE_ROOT) if not Path(entry.path).name.startswith('.')]
    grouped: dict[str, list[RepoEntry]] = {'reports': [], 'notes': [], 'library': []}
    for entry in entries:
        grouped[workspace_bucket(entry.path)].append(entry)

    sections = []
    for key, meta in WORKSPACE_SECTION_META.items():
        items = grouped[key]
        section_items = [
            {
                'path': entry.path,
                'title': workspace_item_title(entry.path),
                'kind': entry.kind,
                'size': entry.size,
                'extension': Path(entry.path).suffix.lower(),
            }
            for entry in items[:6]
        ]
        sections.append({
            'key': key,
            'label': meta['label'],
            'tone': meta['tone'],
            'description': meta['description'],
            'count': len(items),
            'items': section_items,
        })

    storage = []
    for folder, label in [
        ('reports', 'Report artifacts'),
        ('notes', 'Literature notes'),
        ('pdfs', 'PDF library'),
        ('repos', 'Repository captures'),
        ('db', 'Databases'),
    ]:
        folder_entries = [entry for entry in entries if entry.path.startswith(f'{WORKSPACE_ROOT}/{folder}/')]
        storage.append({
            'path': f'{WORKSPACE_ROOT}/{folder}/',
            'label': label,
            'count': len(folder_entries),
            'size': sum(entry.size for entry in folder_entries),
        })

    featured = next((item for item in sections if item['items']), None)
    featured_item = featured['items'][0] if featured else None
    return {
        'root': f'{WORKSPACE_ROOT}/',
        'exists': True,
        'file_count': len(entries),
        'total_size': sum(entry.size for entry in entries),
        'stats': [
            {'label': 'Tracked assets', 'value': len(entries), 'tone': 'purple'},
            {'label': 'Reports', 'value': len(grouped['reports']), 'tone': 'cyan'},
            {'label': 'Literature notes', 'value': len(grouped['notes']), 'tone': 'yellow'},
            {'label': 'Libraries', 'value': len(grouped['library']), 'tone': 'pink'},
        ],
        'sections': sections,
        'storage': storage,
        'featured': featured_item,
    }


def write_repo_index(repo_root: Path, out_path: Path) -> None:
    payload = {
        'summary': summarize_repo(repo_root),
        'tree': build_tree(repo_root),
        'entries': [{'path': entry.path, 'kind': entry.kind, 'size': entry.size} for entry in list_repo_entries(repo_root)],
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2), encoding='utf-8')
